version: '3'

volumes:
  mysql-db:

networks:
  php-tier:

services:

    db:
      image: mysql:5.7
      restart: always
      environment:
        MYSQL_DATABASE: 'db'
        MYSQL_USER: 'user'
        MYSQL_PASSWORD: 'password'
        MYSQL_ROOT_PASSWORD: 'password'
      ports:
        - "3306:3306"
      volumes:
        - mysql-db:/var/lib/mysql

    php:
      build: "php/"
      restart: always
      ports:
        - "8081:8081"
      depends_on:
        - "db"
      networks:
        - php-tier
      environment:
        - HOSTNAME=php
