# Generated by Django 3.1.6 on 2021-07-19 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='No Title', max_length=122, null=True)),
                ('by', models.CharField(blank=True, max_length=122, null=True)),
                ('category', models.CharField(choices=[('rock', 'Rock'), ('classic', 'Classic'), ('hip-hop', 'Hip Hop'), ('r&b', 'R&B'), ('charabia-sans-nom', 'Charabia sans nom')], default='uncategorized', max_length=122)),
                ('file', models.FileField(upload_to='media')),
            ],
        ),
    ]
