# Generated by Django 3.1.6 on 2021-08-06 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicshare', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='date_upload',
        ),
    ]
