# Generated by Django 3.1.6 on 2021-08-02 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicshare', '0002_auto_20210723_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='file',
            field=models.FileField(upload_to='static/'),
        ),
    ]
