# Generated by Django 3.1.6 on 2021-08-03 18:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicshare', '0003_auto_20210802_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='date_upload',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 8, 3, 18, 37, 12, 420357)),
        ),
    ]
