# Generated by Django 3.1.6 on 2021-08-03 19:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('musicshare', '0006_auto_20210803_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='date_upload',
            field=models.DateField(default=datetime.datetime(2021, 8, 3, 19, 35, 41, 621246, tzinfo=utc)),
        ),
    ]
